### ISSUE TITLE
TypeError: this.Connection is not a constructor

### ISSUE THREAD

**Issue by bunchito** [compwright/aws-elasticsearch-connector#21]
This issue was reported here: https://github.com/compwright/aws-elasticsearch-connector/issues/1 and closed
I'm having the same problem.

### I tried on the following environments:
- Node v12.16.1 (npm v6.13.4)
- Node v14.13.1 (npm v6.14.8)

### My package.json
```
{
  "name": "ES",
  "version": "1.0.0",
  "type": "module",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@elastic/elasticsearch": "^7.9.1",
    "aws-elasticsearch-connector": "^9.0.0",
    "aws-sdk": "^2.771.0"
  }
}

### JS file: index.js
```
import * as AWS from 'aws-sdk';
import { Client } from '@elastic/elasticsearch'
import AmazonConnection from 'aws-elasticsearch-connector'

if (process.env.NODE_ENV === 'development') {
  AWS.config.credentials = new AWS.SharedIniFileCredentials({ profile: 'my-profile' });
}

export const esClient = new Client({
  node: 'https://my-vpc-xxxxxxxxxxx-us-east-1.es.amazonaws.com',
  Connection: AmazonConnection
});

```

### Output: `node index.js`

```
/Users/me/es/node_modules/@elastic/elasticsearch/lib/pool/BaseConnectionPool.js:58
    const connection = new this.Connection(opts)
                       ^

TypeError: this.Connection is not a constructor
    at ConnectionPool.createConnection (/Users/me/es/node_modules/@elastic/elasticsearch/lib/pool/BaseConnectionPool.js:58:24)
    at ConnectionPool.update (/Users/me/es/node_modules/@elastic/elasticsearch/lib/pool/BaseConnectionPool.js:155:34)
    at ConnectionPool.update (/Users/me/lalala/es/@elastic/elasticsearch/lib/pool/ConnectionPool.js:220:11)
    at ConnectionPool.addConnection (/Users/me/es/node_modules/@elastic/elasticsearch/lib/pool/BaseConnectionPool.js:91:10)
    at new Client (/Users/me/es/node_modules/@elastic/elasticsearch/index.js:121:27)
    at file:///Users/me/es/index.js:10:25
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

Anyone else is having this issue...?

**Comment by elrob** [comment]
yeah, I was having the same issue and came here.
I upgraded from an older version.
Once I followed the updated README instructions, it worked fine.
https://github.com/compwright/aws-elasticsearch-connector#using-global-configuration

**Comment by akleiber** [comment]
as elrob mentioned this happens when updating to release 9.0.0
